# PreCAWG-Adipose: Figures for sex analyses.
# Refer to `sex_difference_analyses/` for rationale and how the results that are mentioned in this document were originally generated.
# Load library
library(dplyr)
library(MotrpacHumanPreSuspensionAnalysis)
library(readr)
library(ggplot2)
library(tidyverse)
library(ggrepel)
library(patchwork)
library(TMSig)
library(here)

# Set the path to your directory
dir_path <- file.path(here(),
                      "figures",
                      "adipose",
                      "Files")

# Get all .txt file paths in the directory.
#these files were generated by the notebook `baseline_sex_differences`
file_list <- list.files(path = file.path(dir_path, "sex_da"), pattern = "\\.txt$", full.names = TRUE)

# Read all files and combine into one data frame
sex_da <- file_list %>%
  lapply(read_tsv) %>%  # Read each file as a tibble
  bind_rows(.id = "source_file")  # Combine all into one data frame and keep file name info
sex_da <- sex_da %>%
  mutate(assay2 = ifelse(grepl("^metab-", assay), "Metabolomics", assay))
sex_da <- sex_da %>%
  mutate(
    assay2 = recode(assay2,
                    "prot-pr" = "Proteomics",
                    "prot-ph" = "Phosphoproteomics",
                    "transcript-rna-seq" = "Transcriptomics"
    )
  )


sex_da <- sex_da %>%
  mutate(base_feature_id = sub("_.*$", "", feature_id),
         phosphosites = sub("^.*_", "", feature_id) %>%
           gsub("s$", "", .) %>%
           gsub("([STY]\\d+)[a-zA-Z]", "\\1;", .) %>%
           gsub(";$", "", .)) %>%
  group_by(assay2) %>%
  arrange(adj_p_value, .by_group = TRUE) %>%
  mutate(
    rank = row_number(),
    label = case_when(
      rank <= 10 & assay2 == "Phosphoproteomics" ~ paste0(gene_symbol, "-", phosphosites),
      rank <= 10 & assay2 == "Proteomics" ~ as.character(gene_symbol),
      rank <= 10 & assay2 == "Transcriptomics" ~ as.character(gene_symbol),
      rank <= 10 & assay2 == "Metabolomics" ~ as.character(base_feature_id),
      TRUE ~ NA_character_
    )
  ) %>%
  ungroup() %>%
  select(-rank)  # clean up if desired
sex_da <- sex_da %>%
  mutate(color = case_when(
    adj_p_value < 0.05 & logFC > 0 ~ "positive",
    adj_p_value < 0.05 & logFC < 0 ~ "negative",
    TRUE ~ "neutral"
  ))
# Step 1: Count Up and Down
sex_summary <- sex_da %>%
  filter(adj_p_value < 0.05) %>%
  mutate(direction = ifelse(logFC > 0, "Up", "Down")) %>%
  count(assay2, direction) %>%
  pivot_wider(names_from = direction, values_from = n, values_fill = 0) %>%
  mutate(label = paste0(assay2, ": ", Down, " Down / ", Up, " Up"))

# Step 2: Create lookup table for titles
title_map <- setNames(sex_summary$label, sex_summary$assay2)

# Step 3: Update function to accept dynamic title
plot_volcano_sex <- function(omic_type, data, title_map) {
  ggplot(data %>% filter(assay2 == omic_type),
         aes(x = logFC, y = -log10(adj_p_value), color = color)) +
    geom_point(alpha = 0.7, size = 1) +
    scale_color_manual(values = c("negative" = "#f95c6f", "positive" = "#5555ff", "neutral" = "grey50")) +
    geom_vline(xintercept = 0, linetype = "dashed", color = "darkgrey") +
    geom_label_repel(
      aes(label = label),
      size = 2,
      max.overlaps = 10,
      box.padding = 0.1,
      point.padding = 0.1,
      label.padding = 0.1,
      segment.size = 0.2,
      segment.color = "grey50",
      label.size = 0.2,
      fill = "white",
      color = "black"
    ) +
    labs(
      title = title_map[[omic_type]],  # Use dynamically constructed title
      x = "Log Fold Change",
      y = "-log10 Adjusted P-Value"
    ) +
    theme_minimal() +
    theme(
      panel.grid.major = element_line(size = 0.2),
      panel.grid.minor = element_line(size = 0.1),
      legend.position = "none",
      strip.text = element_text(size = 8, face = "bold"),
      panel.border = element_rect(color = "black", fill = NA, linewidth = 0.5)
    )
}

# Step 4: Plot with dynamic titles
p_trans <- plot_volcano_sex("Transcriptomics", sex_da, title_map)
p_prot  <- plot_volcano_sex("Proteomics", sex_da, title_map)
p_phos  <- plot_volcano_sex("Phosphoproteomics", sex_da, title_map)
p_metab <- plot_volcano_sex("Metabolomics", sex_da, title_map)

# Combine
sex_vol <- p_trans + p_prot + p_phos + p_metab
print(sex_vol) # FIgure 1D

## Pathway enrichment
sexdiff_camera <- read.delim(file.path(dir_path, "human-precovid-sed-adu_t11-adipose_all-omes_enrichment_sex_diff_baseline_simple_v1.31.txt"))
sexdiff_camera <- sexdiff_camera %>%
  mutate(assay = recode(assay,
                        "prot-pr" = "Prot.",
                        "transcript-rna-seq" = "Transcript.",
                        "prot-ph" = "Phos.",
                        "metab" = "Metab."))

term1 <- c("GOBP_BRANCHED_CHAIN_AMINO_ACID_METABOLIC_PROCESS",
           "GOBP_BRANCHED_CHAIN_AMINO_ACID_CATABOLIC_PROCESS",
           "GOBP_AEROBIC_RESPIRATION",
           "MITOCARTA_Amino acid metabolism",
           "GOBP_NADH_DEHYDROGENASE_COMPLEX_ASSEMBLY",
           "GOBP_OXIDATIVE_PHOSPHORYLATION",
           "REACTOME_EUKARYOTIC_TRANSLATION_INITIATION",
           "GOCC_PROTEASOME_COMPLEX",
           "GOBP_FATTY_ACID_BETA_OXIDATION",
           "WP_FATTY_ACID_BIOSYNTHESIS",
           "GOBP_TRICARBOXYLIC_ACID_CYCLE",
           "GOCC_IGG_IMMUNOGLOBULIN_COMPLEX",
           "GOCC_CYTOSOLIC_SMALL_RIBOSOMAL_SUBUNIT",
           "REACTOME_SUMOYLATION_OF_DNA_DAMAGE_RESPONSE_AND_REPAIR_PROTEINS",
           "GOBP_REGULATION_OF_ACTIN_FILAMENT_BUNDLE_ASSEMBLY",
           "BIOCARTA_MYOSIN_PATHWAY",
           "GOBP_POSITIVE_REGULATION_OF_STRESS_FIBER_ASSEMBLY",
           "GOBP_PLATELET_DERIVED_GROWTH_FACTOR_RECEPTOR_BETA_SIGNALING_PATHWAY")

# subset Transcriptomics + Proteomics data with curated terms.
sexdiff_camera_t_pr_subset <- sexdiff_camera %>%
  filter(set %in% term1)

# Figure 1E
sexdiff_camera_t_pr_subset %>%
  enrichmap(n_top = Inf,
            plot_sig_only = FALSE,
            colors = c("#f95c6f", "#5555ff"),
            set_column = "set_short",
            statistic_column = "z.std",
            contrast_column = "assay",
            padj_column = "adj_p_value",
            padj_legend_title = "BH Adjusted\nP-Value",
            heatmap_args = list(
              heatmap_legend_param = list(title = "Z-Score"),
              show_column_names = TRUE
            ))

# Figure 1F
sexdiff_camera %>%
  filter(assay == "Phos.", adj_p_value<0.05) %>%
  enrichmap(n_top = Inf,
            colors = c("#f95c6f", "#5555ff"),
            set_column = "set_short",
            statistic_column = "z.std",
            contrast_column = "assay",
            padj_column = "adj_p_value",
            padj_legend_title = "BH Adjusted\nP-Value",
            heatmap_args = list(
              heatmap_legend_param = list(title = "Z-Score"),
              show_column_names = TRUE
            ))

# Figure 1G
sexdiff_camera %>%
  filter(assay == "Metab.", adj_p_value<0.1) %>%
  enrichmap(n_top = Inf,
            set_column = "set_short",
            plot_sig_only = FALSE,
            colors = c("#f95c6f", "#5555ff"),
            statistic_column = "z.std",
            contrast_column = "assay",
            padj_column = "adj_p_value",
            padj_legend_title = "BH Adjusted\nP-Value",
            heatmap_args = list(
              heatmap_legend_param = list(title = "Z-Score"),
              show_column_names = TRUE
            ))


