---
title: "Blood_Proteomics_Adipose_RNA_Proteomics_Genes_Heatmap"
author: "Gaurav Tiwari"
date: "2025-11-08"
output: html_document
---


```{r setup, include=FALSE}
session_packages = c("dplyr", "ggplot2", "ggrepel", "stringr", "scales","tidyverse", "ComplexUpset","MotrpacHumanPreSuspension", "MotrpacHumanPreSuspensionData", "tidyr", "ComplexHeatmap", "circlize", "RColorBrewer", "grid","openxlsx", "stringr", "purrr")
for (lib_name in session_packages){
  tryCatch({library(lib_name,character.only = T)}, error = function(e) {
    print(paste("Cannot load",lib_name,", please install"))
  })
}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

theme_set(theme_minimal())
```


```{r session setup}
# Save date in case output files requiring date version
date <- Sys.Date()
date <- gsub("-", "", date)

# setwd(file.path(normalizePath(config$local_path), "precovid-analyses", "integrative"))
# Load libraries
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/unsupervised_normalization_functions.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/gcp_functions.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/qc_report_aux_functions.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/config_session.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/association_analysis_methods.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/MetabolomicsLibrary.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/metabolomics_data_parsing_functions.R"))
# source(file.path(normalizePath(config$general_shared_functions_library)))
# repo_local_dir = file.path(config$precovid_repo_path, "data", "tmp")
repo_local_dir = NULL
library(here)
here::i_am("figures/blood/final_figure_codes/Figure_6/Fig_6C.Rmd")
data_dir       <- here("figures", "blood", "final_figure_input_data_files")
plot_dir       <- here("figures", "blood", "final_figures")
output_data_dir <- here("figures", "blood", "final_output_files")

source(here("figures", "blood", "final_figure_codes", "Figure_6", "generate_sig_genes_heatmap_tissues_combined.R"))

```


```{r, message=FALSE, warning=FALSE}

# repo_local_dir = "/Users/gauravtiwari/BIDMC/MoTrPAC/motrpac_new/pre_cawg/Gaurav"

generate_heatmap_interactive3(
  repo_local_dir = repo_local_dir,
  secprot_path = file.path(data_dir, "sec_prot_cell.csv"),
  supplemental_excel = file.path(data_dir, "Supplemental Tables.xlsx"),
  figure_path = file.path(plot_dir, "Figure_6" ,"Fig6C.pdf"),
  tissue_type = "adipose"
)


```

