---
title: "Single_Feature_Plots"
author: "Gaurav Tiwari"
date: "2025-11-08"
output: html_document
---


```{r setup, include=FALSE}
session_packages = c("dplyr", "ggplot2", "ggrepel", "stringr", "scales","tidyverse", "ComplexUpset","MotrpacHumanPreSuspension", "MotrpacHumanPreSuspensionData","openxlsx")
for (lib_name in session_packages){
  tryCatch({library(lib_name,character.only = T)}, error = function(e) {
    print(paste("Cannot load",lib_name,", please install"))
  })
}

knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

theme_set(theme_minimal())
```


```{r session setup}
# Save date in case output files requiring date version
date <- Sys.Date()
date <- gsub("-", "", date)

# setwd(file.path(normalizePath(config$local_path), "precovid-analyses", "integrative"))
# Load libraries
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/unsupervised_normalization_functions.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/gcp_functions.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/qc_report_aux_functions.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/config_session.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/association_analysis_methods.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/MetabolomicsLibrary.R"))
# source(file.path(normalizePath(config$motrpac_bic_norm_qc_repo_path),"tools/metabolomics_data_parsing_functions.R"))
# source(file.path(normalizePath(config$general_shared_functions_library)))
# repo_local_dir = file.path(config$precovid_repo_path, "data", "tmp")
repo_local_dir = NULL
library(here)
here::i_am("figures/blood/final_figure_codes/Figure_7/Fig_7E.Rmd")
data_dir       <- here("figures", "blood", "final_figure_input_data_files")
plot_dir       <- here("figures", "blood", "final_figures")
output_data_dir <- here("figures", "blood", "final_output_files")

```



```{r, message=FALSE, warning=FALSE}


plot_object1_blood <- MotrpacHumanPreSuspension::plot_single_feature(feature = "ENSG00000168439.17",repo_local_dir = NULL,selected_tissues = "blood",selected_omes = "transcript-rna-seq",output_file = file.path(plot_dir,"Figure_7" ,"Figure_7E_STIP1_ENSG00000168439_17_blood.pdf"))

plot_object1_muscle <- MotrpacHumanPreSuspension::plot_single_feature(feature = "ENSG00000168439.17",repo_local_dir = NULL,selected_tissues = "muscle",selected_omes = "transcript-rna-seq",output_file = file.path(plot_dir,"Figure_7" ,"Figure_7E_STIP1_ENSG00000168439_17_muscle.pdf"))

plot_object2_blood <- MotrpacHumanPreSuspension::plot_single_feature(feature = "ENSG00000080824.19",repo_local_dir = NULL,selected_tissues = "blood",selected_omes = "transcript-rna-seq",output_file = file.path(plot_dir,"Figure_7" ,"Figure_7E_HSP90AA1_ENSG00000080824_19_blood.pdf"))

plot_object2_muscle <- MotrpacHumanPreSuspension::plot_single_feature(feature = "ENSG00000080824.19",repo_local_dir = NULL,selected_tissues = "muscle",selected_omes = "transcript-rna-seq",output_file = file.path(plot_dir,"Figure_7" ,"Figure_7E_HSP90AA1_ENSG00000080824_19_muscle.pdf"))

plot_object3_blood <- MotrpacHumanPreSuspension::plot_single_feature(feature = "ENSG00000127824.15",repo_local_dir = NULL,selected_tissues = "blood",selected_omes = "transcript-rna-seq",output_file = file.path(plot_dir,"Figure_7" ,"Figure_7E_TUBA4A_ENSG00000127824_15_blood.pdf"))

plot_object3_muscle <- MotrpacHumanPreSuspension::plot_single_feature(feature = "ENSG00000127824.15",repo_local_dir = NULL,selected_tissues = "muscle",selected_omes = "transcript-rna-seq",output_file = file.path(plot_dir,"Figure_7" ,"Figure_7E_TUBA4A_ENSG00000127824_15_muscle.pdf"))

plot_object4_blood <- MotrpacHumanPreSuspension::plot_single_feature(feature = "ENSG00000204389.10",repo_local_dir = NULL,selected_tissues = "blood",selected_omes = "transcript-rna-seq",output_file = file.path(plot_dir,"Figure_7" ,"Figure_7E_HSPA1A_ENSG00000204389_10_blood.pdf"))

plot_object4_muscle <- MotrpacHumanPreSuspension::plot_single_feature(feature = "ENSG00000204389.10",repo_local_dir = NULL,selected_tissues = "muscle",selected_omes = "transcript-rna-seq",output_file = file.path(plot_dir,"Figure_7" ,"Figure_7E_HSPA1A_ENSG00000204389_10_muscle.pdf"))

```

